# Generated by Django 6.0.6 on 2026-06-21 06:05

import django.db.models.deletion
import uuid
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ProductID", models.BigIntegerField(unique=True)),
                ("ProductCode", models.CharField(max_length=255, unique=True)),
                ("ProductName", models.CharField(max_length=255)),
                (
                    "ProductImage",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="uploads/"
                    ),
                ),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("UpdatedDate", models.DateTimeField(blank=True, null=True)),
                ("IsFavourite", models.BooleanField(default=False)),
                ("Active", models.BooleanField(default=True)),
                ("HSNCode", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "TotalStock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=0.0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "CreatedUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "products_product",
                "ordering": ("-CreatedDate", "ProductID"),
                "unique_together": {("ProductCode", "ProductID")},
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.products",
                    ),
                ),
            ],
            options={
                "db_table": "product_variant",
            },
        ),
        migrations.CreateModel(
            name="SubVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=255, unique=True)),
                ("combination_key", models.CharField(db_index=True, max_length=500)),
                (
                    "stock",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subvariants",
                        to="core.products",
                    ),
                ),
            ],
            options={
                "db_table": "product_subvariant",
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("PURCHASE", "Purchase"), ("SALE", "Sale")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transactions",
                        to="core.products",
                    ),
                ),
                (
                    "subvariant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transactions",
                        to="core.subvariant",
                    ),
                ),
            ],
            options={
                "db_table": "stock_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "variant_option",
            },
        ),
        migrations.AddField(
            model_name="subvariant",
            name="options",
            field=models.ManyToManyField(
                related_name="subvariants", to="core.variantoption"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product"], name="product_var_product_bcaee9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "name")},
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["product"], name="stock_trans_product_cc413b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["subvariant"], name="stock_trans_subvari_75e9fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["transaction_type"], name="stock_trans_transac_c3f401_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["created_at"], name="stock_trans_created_ece84f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variantoption",
            index=models.Index(
                fields=["variant"], name="variant_opt_variant_a0973a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variantoption",
            unique_together={("variant", "value")},
        ),
        migrations.AddIndex(
            model_name="subvariant",
            index=models.Index(
                fields=["product"], name="product_sub_product_7322b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subvariant",
            index=models.Index(
                fields=["combination_key"], name="product_sub_combina_ffbe90_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subvariant",
            unique_together={("product", "combination_key")},
        ),
    ]
