# Generated by Django 6.0.6 on 2026-06-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)), name="subvariant_stock_gte_0"
            ),
        ),
    ]
