# Generated by Django 6.0.6 on 2026-06-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_subvariant_subvariant_stock_gte_0"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subvariant",
            options={"ordering": ["id"]},
        ),
    ]
